### PR TITLE
Capture and detect

### PR DESCRIPTION
**Pull request by Hamlob**
Included 2 classes: camera for frame capture and filter for filtering the coordinates. For each there is a simple test code too.

### CODE REVIEW

**Comment by Jenibluere** [comment]
@ me when you resolved the weird error with the camera @Hamlob :)

**Comment by Hamlob** [comment]
The filter and camera classes now fully working with tests written in filterTest.cpp and cameraTest.cpp

**Comment by Jenibluere** [comment]
cameraTest.cpp and filterTest.cpp aren't in the `src` directory. Could you move?
There's no makefile as of yet. I can help you make one - what build options are you using/any compiler preference?

**Review by Jenibluere — CHANGES_REQUESTED** [review]
Requires Makefile and a fix to the file structure. See my earlier comment.

**Comment by Jenibluere** [comment]
Reminder to merge main into your branch before you continue with this pull request.

**Review by Jenibluere — DISMISSED** [review]

**Comment by Jenibluere** [comment]
```
$ ./wake-o-matic-main

(wake-o-matic-main:7540): GStreamer-CRITICAL **: 17:13:48.783: gst_element_get_state: assertion 'GST_IS_ELEMENT (element)' failed
Camera started
Frame processing started
Action state machine started
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.0.0) /home/pi/OpenCV_NEW/opencv-4.0.0/modules/objdetect/src/cascadedetect.cpp:1658: error: (-215:Assertion failed) !empty() in function 'detectMultiScale'

Aborted
```

**Pull request closed without merging**
